name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5433f1e0bcd307ad64d0c0d3ef90b38fbb70365f731a30430491f50e367c987e"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
